### ISSUE TITLE
[account] Support rotate authentication key 

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#1052]
New feature: add rotate-authentication-key as subcommand of starcoin/account

This cmd will do:

1. rotate auth key by private key(as a arg)
2. re-import account
3. must be idempotent

------ origin issue ----

Support rotate_authentication_key command

1. Read or generate a new private key
4. execute script function Account::rotate_authentication_key
5. change the private key of the account in the node wallet.
6. finished the documents https://github.com/starcoinorg/starcoin-cookbook/blob/main/docs/02-getting-started/03-accounts/4.rotate-authentication-key.md

**Comment by jolestar** [comment]
A command example:

```
场景

重置账号B的私钥，且address不变。

准备新账号A，用A的auth key替换B的auth key，再重新导入账号B。

 

### 账号A：

account show 0x824517355d6081430afcc9f3c7179118

{

  "ok": {

    "account": {

      "address": "0x824517355d6081430afcc9f3c7179118",

    },

    "auth_key":  "{{A的auth key}}",

  }

}

 

### 账号B：

account show 0x838a1e3c03d4f5b9ce4a475da7aa6f72

{

  "ok": {

    "account": {

      "address": "0x838a1e3c03d4f5b9ce4a475da7aa6f72",

    },

    "auth_key": "{{B的auth key}}",

  }

}

 

### 更新auth key，用账号A的auth key更新账号B，更新成功

account execute-function -s 0x838a1e3c03d4f5b9ce4a475da7aa6f72 --function 0x1::Account::rotate_authentication_key  --arg x"{{A的auth key}}"  -b

 

### remove账号A

account remove 0x824517355d6081430afcc9f3c7179118

 

### remove账号B

account remove 0x838a1e3c03d4f5b9ce4a475da7aa6f72

 

### 重新用A的私钥导入，并指定账号B的address，达到账号B的私钥被重置的效果

account import -i {{账号A的私钥}}  {{账号B address}}
```

**Comment by templexxx** [comment]
> Support rotate_authentication_key command
> 
> 1. Read or generate a new private key
> 2. execute script function Account::rotate_authentication_key
> 3. change the private key of the account in the node wallet.
> 4. finished the documents https://github.com/starcoinorg/starcoin-cookbook/blob/main/docs/02-getting-started/03-accounts/4.rotate-authentication-key.md

@jolestar 

I don't think generate private key inside rotate_authentication_key command is a good idea. Because we may lost the private key when corruption after remove account (but import hasn't been executed). The whole node may corrupt and cannot be set up anymore, so the keypair will lost forever, which means this account will have a invaild auth_key on chain forever.

Pass private_key as cmd arg is the only solution to protect account:

1. If node exit unexpected after rotate script execution(we will get invalid_auth key error): remove account and import with new private key manually.
2. If node exit unexpected after remove(account not existed): import with new private key manually.
