### ISSUE TITLE
Cli normal quit when node shutdown.

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starcoin#136]
RPCClient 实现优雅关闭以及自动重连接。

当 node 关闭时， 正在通过 console 连接的 cli 会 panic ：

starcoin% 2020-04-07T19:25:38.824683+08:00 WARN jsonrpc_client_transports::transports::ipc::/Users/jolestar/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-client-transports-14.0.5/src/transports/ipc.rs::27 - IPC client error: Other(Custom { kind: Other, error: "bytes remaining on stream" }

需要改造为正常退出。

**Comment by lerencao** [comment]
> starcoin% 2020-04-07T19:25:38.824683+08:00 WARN jsonrpc_client_transports::transports::ipc::/Users/jolestar/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpc-client-transports-14.0.5/src/transports/ipc.rs::27 - IPC client error: Other(Custom { kind: Other, error: "bytes remaining on stream" }

This's a log recorded by json-rpc library when the ipc channel is gone. Besides this, I didn't see panic on `console` cli after the node is down.

I make a change in #190  to rpc client which can do auto-reconnect action in ipc mode if rpc request failed due to unix-socket error (socket is lost, or socket io error).

**Comment by lerencao** [comment]
Now txfactory can send requests after node restart.

**Comment by lerencao** [comment]
closed now.
