### ISSUE TITLE
[Bug Report] Missing openssl 1.1  in v1.11.7-rc on ubuntu 22.04

### ISSUE THREAD

**Issue by WGB5445** [starcoinorg/starcoin#3382]
# Bug Report

**Starcoin version:**

v1.11.7-rc 
**Current behavior:**
Missing openssl 1.1 using mpm-ubuntu-last in v1.11.7-rc on ubuntu 22.04

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

**Other information:**

![image](https://user-images.githubusercontent.com/6522980/166393069-dab68908-6978-4c00-aba2-90145ba8b051.png)

**Comment by yourmoonlight** [comment]
Hi @WGB5445 [WGB5445](https://github.com/WGB5445)

The reason is that ubuntu 22.04 upgraded OpenSSL to version 3.0, however the latest [openssl crate](https://docs.rs/openssl/latest/openssl/) have not support OpenSSL 3.0 

So here's the workaround, we can manually install the OpenSSL 1.1.1 by doing the following steps and everything will be fine.

`
cd /tmp
wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
tar -vzxf openssl-1.1.1o.tar.gz
cd openssl-1.1.1o/
./config
make install
**export LD_LIBRARY_PATH=/usr/local/lib** This is needed
`

And btw maybe you need temporally disable the IPV6, here's the cmd:
`
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
`

After the instruction, something should be like this
`
root@xx:~/starcoin-artifacts# ./starcoin -V
./starcoin: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
root@xx:~/starcoin-artifacts# export LD_LIBRARY_PATH=/usr/local/lib
root@xx:~/starcoin-artifacts# ./starcoin -V
starcoin 1.11.7-rc
`

**Comment by jolestar** [comment]
Why do we need to disable IPV6?

**Comment by yourmoonlight** [comment]
> Why do we need to disable IPV6?

When I wget the openssl tar,  it stucked. Something wrong with the network, so I disabled the IPV6, then the downloading process can proceed on

**Comment by WGB5445** [comment]
Thank you very much for your help, I have successfully run Starcoin according to the above operation process
If the latest openssl crate supports openssl 3.0 in the future, I believe this problem will be completely solved

**Comment by WGB5445** [comment]
I don't need to turn off ipv6 here, I think it may be a difference in the operating environment

**Comment by jolestar** [comment]
#3784
